title: "Deterministic Blog"
author: "Mehmet Kutay Bozkurt"
description: "Made with <b style=\"color: #bf616a;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "about.md", url: "/about/", title: "About"}
  - {file: "archive.html", url: "/archive/", title: "Archive"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail", icon: "envelope", url: "mailto:mkutaybzkrt01101011@gmail.com", include_title: false}
  - {title: "Github", icon: "github", url: "https://github.com/MKutay", include_title: false}
  - {title: "Subscribe", icon: "rss", url: "/feed.xml", include_title: false}
  - {title: "Sponsor Me", icon: "heart", url: "https://github.com/sponsors/MKutay?o=esb", include_title: true}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

include: ["_pages"]
